# yamllint disable rule:line-length
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Cleanup tests

on:  # yamllint disable-line rule:truthy
  push:

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Free extra space
        run: |
          echo "Initial free space"
          df -h /
          echo "Removing all pre-loaded docker images"
          docker rmi $(docker image ls -aq)  # Removes ~4GB
          df -h /
          # echo "Listing 100 largest packages"
          # dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -rn | head -n 100
          echo "Removing unneeded large packages"
          sudo apt-get update
          sudo apt-get remove -y '^ghc-.*' '^dotnet-.*' hhvm azure-cli google-cloud-sdk powershell google-chrome-stable firefox microsoft-edge-stable 'php.*' 'mongodb-*' 'mysql-*' 'mariadb-*' 'adoptopenjdk-.*-hotspot' 'temurin-*' 'openjdk-*' default-jre-headless
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h /
          echo "Removing remaining large directories"
          rm -rf /usr/share/dotnet/  # Removes ~1GB
          df -h /
          rm -rf "$AGENT_TOOLSDIRECTORY"  # Removes ~7GB
          echo "Disk space after cleanup"
          df -h /
          pwd
          df -h $(pwd)
