# yamllint disable rule:line-length
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Cleanup tests

on:  # yamllint disable-line rule:truthy
  push:

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Free extra space
        run: |
          set -x
          echo "Initial free space"
          df -h / /mnt
          docker rmi $(docker image ls -aq)  # Removes ~4GB
          df -h / /mnt
          # echo "Listing 100 largest packages"
          # dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -rn | head -n 100
          echo "Removing large packages"
          sudo apt-get update
          sudo apt-get remove -y '^ghc-.*' '^dotnet-.*' hhvm
          sudo apt-get remove -y azure-cli google-cloud-sdk powershell
          sudo apt-get remove -y google-chrome-stable firefox microsoft-edge-stable
          sudo apt-get remove -y 'php.*' 'mongodb-*' 'mysql-*' 'mariadb-*'
          sudo apt-get remove -y 'adoptopenjdk-.*-hotspot' 'temurin-*'
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h / /mnt
          echo "Removing remaining large directories"
          rm -rf /usr/share/dotnet/
          df -h / /mnt
          rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "Disk space after cleanup"
          df -h / /mnt
